export const ELIGIBILITY_PROGRAM_ID =
  "PHYwVLxfos5STGcSzFe9Jirzy6YiEPPZC3wVKoTHoER";

export const EPOCH_REGISTRY_PROGRAM_ID =
  "PHYcBRWd6mKATk3xo8oYi3d55BBHUc7kAN4kK91cJoE";

export const GOVERNANCE_MODE_PRIVE_ONLY = 1;

export const ELIGIBILITY_REGISTRY_VERSION = 1;
export const ELIGIBILITY_CLASS_VERSION = 1;
export const ELIGIBILITY_RECORD_VERSION = 2;
export const ISSUER_GRANT_VERSION = 1;

export const NAME_BYTES = 32;
export const LABEL_BYTES = 16;
export const SUBJECT_KEY_BYTES = 32;
export const METADATA_HASH_BYTES = 32;

export const CLASS_ID_PRIVE_MEMBER = 1;
export const CLASS_ID_PERSONA_VERIFIED = 2;

export const CLASS_KIND_PRIVE_MEMBER = 1;
export const CLASS_KIND_PERSONA_VERIFIED = 2;

export const CLASS_STATUS_DRAFT = 0;
export const CLASS_STATUS_ACTIVE = 1;
export const CLASS_STATUS_DISABLED = 2;
export const CLASS_STATUS_DEPRECATED = 3;

export const SUBJECT_KIND_WALLET = 1;
export const SUBJECT_KIND_PERSONA_HASH = 2;
export const SUBJECT_KIND_EXTERNAL_ATTESTATION = 3;

export const RECORD_STATUS_PENDING = 0;
export const RECORD_STATUS_ACTIVE = 1;
export const RECORD_STATUS_SUSPENDED = 2;
export const RECORD_STATUS_REVOKED = 3;
export const RECORD_STATUS_EXPIRED = 4;

export const ELIGIBILITY_SOURCE_UNKNOWN = 0;

export const
  ELIGIBILITY_SOURCE_DAO_GOVERNANCE_OVERRIDE = 1;

export const
  ELIGIBILITY_SOURCE_PRIVE_COLLECTION_ATTESTATION = 2;

export const
  ELIGIBILITY_SOURCE_PERSONA_ATTESTATION = 3;

export const
  ELIGIBILITY_SOURCE_MANUAL_COUNCIL_DEPRECATED = 4;

export const ISSUER_PERMISSION_CREATE = 1;
export const ISSUER_PERMISSION_REFRESH = 1 << 1;
export const ISSUER_PERMISSION_ACTIVATE_PENDING = 1 << 2;
export const ISSUER_PERMISSION_SUSPEND = 1 << 3;
export const ISSUER_PERMISSION_EXPIRE = 1 << 4;

export const ISSUER_PERMISSION_ALL =
  ISSUER_PERMISSION_CREATE |
  ISSUER_PERMISSION_REFRESH |
  ISSUER_PERMISSION_ACTIVATE_PENDING |
  ISSUER_PERMISSION_SUSPEND |
  ISSUER_PERMISSION_EXPIRE;

// Temporary aliases retained until the delegated record instruction
// migration updates every remaining test and operational script.
export const ELIGIBILITY_SOURCE_DAO_APPROVED =
  ELIGIBILITY_SOURCE_DAO_GOVERNANCE_OVERRIDE;

export const
  ELIGIBILITY_SOURCE_PRIVE_COLLECTION_VERIFIED =
    ELIGIBILITY_SOURCE_PRIVE_COLLECTION_ATTESTATION;

export const ELIGIBILITY_SOURCE_MANUAL_COUNCIL =
  ELIGIBILITY_SOURCE_MANUAL_COUNCIL_DEPRECATED;
