export const ELIGIBILITY_PROGRAM_ID =
  "PHYwVLxfos5STGcSzFe9Jirzy6YiEPPZC3wVKoTHoER";

export const GOVERNANCE_MODE_PRIVE_ONLY = 1;

export const ELIGIBILITY_REGISTRY_VERSION = 1;
export const ELIGIBILITY_CLASS_VERSION = 1;
export const ELIGIBILITY_RECORD_VERSION = 1;

export const NAME_BYTES = 32;
export const LABEL_BYTES = 16;
export const SUBJECT_KEY_BYTES = 32;
export const METADATA_HASH_BYTES = 32;

export const CLASS_ID_PRIVE_MEMBER = 1;
export const CLASS_ID_PERSONA_VERIFIED = 2;

export const CLASS_KIND_PRIVE_MEMBER = 1;
export const CLASS_KIND_PERSONA_VERIFIED = 2;

export const CLASS_STATUS_DRAFT = 0;
export const CLASS_STATUS_ACTIVE = 1;
export const CLASS_STATUS_DISABLED = 2;
export const CLASS_STATUS_DEPRECATED = 3;

export const SUBJECT_KIND_WALLET = 1;
export const SUBJECT_KIND_PERSONA_HASH = 2;
export const SUBJECT_KIND_EXTERNAL_ATTESTATION = 3;

export const RECORD_STATUS_PENDING = 0;
export const RECORD_STATUS_ACTIVE = 1;
export const RECORD_STATUS_SUSPENDED = 2;
export const RECORD_STATUS_REVOKED = 3;
export const RECORD_STATUS_EXPIRED = 4;

export const ELIGIBILITY_SOURCE_UNKNOWN = 0;
export const ELIGIBILITY_SOURCE_DAO_APPROVED = 1;
export const ELIGIBILITY_SOURCE_PRIVE_COLLECTION_VERIFIED = 2;
export const ELIGIBILITY_SOURCE_PERSONA_ATTESTATION = 3;
export const ELIGIBILITY_SOURCE_MANUAL_COUNCIL = 4;
